let userName = prompt("Здарова, твое имя?")
alert("Значит тебя зовут" + " .::" + userName +":..")
console.log(`Name - ${userName}`)
let userAge = prompt("Сколько тебе лет?")
alert(`Тебя зовут ${userName} и тебе ${userAge} лет!`)
console.log(`Age - ${userAge} лет!`)
let userGeopos = prompt("В Каком городе ты проживаешь?")
alert(`Тебя зовут ${userName}, тебе ${userAge} лет, ты проживаешь в городе ${userGeopos}`)
console.log(`Live - ${userGeopos}`)


/* let userName = prompt("Здарова, твое имя?")
alert("Значит тебя зовут" + " .::" + userName +":..")
console.log(`Пользователь ввел имя - ${userName}`)
let userAge = prompt("Сколько тебе лет?")
alert(`Тебя зовут ${userName} и тебе ${userAge} лет!`)
console.log(`Пользователю - ${userAge} лет!`)
let userGeopos = prompt("В Каком городе ты проживаешь?")
alert(`Тебя зовут ${userName}, тебе ${userAge} лет, ты проживаешь в городе ${userGeopos}`)
console.log(`Пользователь ввел город проживания - ${userGeopos}`)
 */